/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

/**
 *
 * @author PC
 */
import java.io.*;
import java.sql.*;
import javax.swing.*;
public class show_tables extends javax.swing.JFrame {

    /**
     * Creates new form show_tables
     */
    public show_tables() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pr = new javax.swing.JTextArea();
        players = new javax.swing.JButton();
        championships = new javax.swing.JButton();
        presentation = new javax.swing.JButton();
        Sponsoring_Companies = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pr.setColumns(20);
        pr.setRows(5);
        jScrollPane1.setViewportView(pr);

        players.setText("players");
        players.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playersMouseClicked(evt);
            }
        });

        championships.setText("championships");
        championships.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                championshipsMouseClicked(evt);
            }
        });

        presentation.setText("presentation");
        presentation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                presentationMouseClicked(evt);
            }
        });

        Sponsoring_Companies.setText("Sponsors");
        Sponsoring_Companies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sponsoring_CompaniesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(players, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(championships)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(presentation)
                .addGap(18, 18, 18)
                .addComponent(Sponsoring_Companies)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(players)
                    .addComponent(championships)
                    .addComponent(presentation)
                    .addComponent(Sponsoring_Companies))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playersMouseClicked
        // TODO add your handling code here:
        
         try
           {
                    ////////////////// drag the database MS access file to the Source Package folder
                    File f=new File("E://AlAhly.mdb");
                    
                    Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                    Connection con=DriverManager.getConnection("jdbc:ucanaccess://"+f.getAbsolutePath());
                    Statement s=con.createStatement();
                    ResultSet rs=s.executeQuery("select * from players");
                    
                    ////////////// to get Number of Attributes
                    ResultSetMetaData rsmd = rs.getMetaData();
                    int columnsNumber = rsmd.getColumnCount();
                    String p="";
                    ////////////// to get Names of Attributes
                    for(int i=1;i<=columnsNumber;i++)
                        {
                        p+=(rsmd.getColumnName(i)+"\t\t\t");
                        }
                        p+="\n";

                    while(rs.next())
                    {
                        
                        for(int j=1;j<=columnsNumber;j++)
                        {
                        p+=(rs.getString(j)+"\t\t\t");
                        }
                        p+="\n";
                       
                    }
                    
                    pr.setText(p);
            }
             catch (Exception e)
             {
                   JOptionPane.showMessageDialog(null,e.toString());
             }
        
    }//GEN-LAST:event_playersMouseClicked

    private void championshipsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_championshipsMouseClicked
        // TODO add your handling code here:
        
        try
           {
                    ////////////////// drag the database MS access file to the Source Package folder
                    File f=new File("E://AlAhly.mdb");
                    
                    Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                    Connection con=DriverManager.getConnection("jdbc:ucanaccess://"+f.getAbsolutePath());
                    Statement s=con.createStatement();
                    ResultSet rs=s.executeQuery("select * from championships");
                    
                    ////////////// to get Number of Attributes
                    ResultSetMetaData rsmd = rs.getMetaData();
                    int columnsNumber = rsmd.getColumnCount();
                    String p="";
                    ////////////// to get Names of Attributes
                    for(int i=1;i<=columnsNumber;i++)
                        {
                        p+=(rsmd.getColumnName(i)+"\t\t\t");
                        }
                        p+="\n";

                    while(rs.next())
                    {
                        
                        for(int j=1;j<=columnsNumber;j++)
                        {
                        p+=(rs.getString(j)+"\t\t\t");
                        }
                        p+="\n";
                       
                    }
                    
                    pr.setText(p);
            }
             catch (Exception e)
             {
                   JOptionPane.showMessageDialog(null,e.toString());
             }
        
    }//GEN-LAST:event_championshipsMouseClicked

    private void presentationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_presentationMouseClicked
        // TODO add your handling code here:
        
        try
           {
                    ////////////////// drag the database MS access file to the Source Package folder
                    File f=new File("E://AlAhly.mdb");
                    
                    Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                    Connection con=DriverManager.getConnection("jdbc:ucanaccess://"+f.getAbsolutePath());
                    Statement s=con.createStatement();
                    ResultSet rs=s.executeQuery("select * from presentation");
                    
                    ////////////// to get Number of Attributes
                    ResultSetMetaData rsmd = rs.getMetaData();
                    int columnsNumber = rsmd.getColumnCount();
                    String p="";
                    ////////////// to get Names of Attributes
                    for(int i=1;i<=columnsNumber;i++)
                        {
                        p+=(rsmd.getColumnName(i)+"\t\t\t");
                        }
                        p+="\n";

                    while(rs.next())
                    {
                        
                        for(int j=1;j<=columnsNumber;j++)
                        {
                        p+=(rs.getString(j)+"\t\t\t");
                        }
                        p+="\n";
                       
                    }
                    
                    pr.setText(p);
            }
             catch (Exception e)
             {
                   JOptionPane.showMessageDialog(null,e.toString());
             }
    }//GEN-LAST:event_presentationMouseClicked

    private void Sponsoring_CompaniesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sponsoring_CompaniesMouseClicked
        // TODO add your handling code here:
         try
           {
                    ////////////////// drag the database MS access file to the Source Package folder
                    File f=new File("E://AlAhly.mdb");
                    
                    Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                    Connection con=DriverManager.getConnection("jdbc:ucanaccess://"+f.getAbsolutePath());
                    Statement s=con.createStatement();
                    ResultSet rs=s.executeQuery("select * from Sponsoring_Companies");
                    
                    ////////////// to get Number of Attributes
                    ResultSetMetaData rsmd = rs.getMetaData();
                    int columnsNumber = rsmd.getColumnCount();
                    String p="";
                    ////////////// to get Names of Attributes
                    for(int i=1;i<=columnsNumber;i++)
                        {
                        p+=(rsmd.getColumnName(i)+"\t\t\t");
                        }
                        p+="\n";

                    while(rs.next())
                    {
                        
                        for(int j=1;j<=columnsNumber;j++)
                        {
                        p+=(rs.getString(j)+"\t\t\t");
                        }
                        p+="\n";
                       
                    }
                    
                    pr.setText(p);
            }
             catch (Exception e)
             {
                   JOptionPane.showMessageDialog(null,e.toString());
             }
        
    }//GEN-LAST:event_Sponsoring_CompaniesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(show_tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(show_tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(show_tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(show_tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new show_tables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sponsoring_Companies;
    private javax.swing.JButton championships;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton players;
    private javax.swing.JTextArea pr;
    private javax.swing.JButton presentation;
    // End of variables declaration//GEN-END:variables
}
